#!/usr/bin/env python3
"""Extract the corpus into the plain-text outputs the work consumes.

The corpus holds period documents as PDFs; the records name what each
item is FOR, but nothing downstream reads a PDF. This tool is the one
deterministic path from the curated items to text: it reads
corpus/manifest.md, extracts every item's pages with pypdf, and
writes one plain-text file per item under corpus/out/ plus an index
of derived facts (pages, words). No timestamps, no randomness - two
runs over the same corpus produce byte-identical outputs, the same
law the sister's reproducible jar follows.

The outputs are derived artifacts, not curation: everything a text
file says is in its PDF, and the manifest remains the record. An
item enters the corpus by curation (README law); it enters the
outputs by being in the manifest, and never otherwise.
"""

from __future__ import annotations

import pathlib
import re
import sys

try:
    from pypdf import PdfReader
except ImportError:
    from PyPDF2 import PdfReader

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "corpus" / "manifest.md"
TEXT_DIR = ROOT / "corpus" / "text"
OUT_DIR = ROOT / "corpus" / "out"

ENTRY_RE = re.compile(r"^## (\d{4}) - (.+)$")
TEXT_RE = re.compile(r"^- Text: `([^`]+)`")


def read_manifest() -> list[tuple[str, str, str]]:
    """The manifest is the only authority for what has an output.

    Returns (id, title, text-path) in manifest order.
    """
    items: list[tuple[str, str, str]] = []
    entry_id, title, text = None, None, None
    with MANIFEST.open(encoding="utf-8") as handle:
        for line in handle:
            match = ENTRY_RE.match(line)
            if match:
                if entry_id is not None and text is not None:
                    items.append((entry_id, title, text))
                entry_id, title, text = match.group(1), match.group(2), None
                continue
            if entry_id is not None and text is None:
                text_match = TEXT_RE.match(line)
                if text_match:
                    text = text_match.group(1)
    if entry_id is not None and text is not None:
        items.append((entry_id, title, text))
    return items


def extract(item_id: str, title: str, text_path: str) -> tuple[pathlib.Path, int, int]:
    source = ROOT / "corpus" / text_path
    if not source.is_file():
        raise SystemExit(f"FAULT: manifest item {item_id} names a missing file: {text_path}")

    reader = PdfReader(str(source))
    pages: list[str] = []
    words = 0
    for number, page in enumerate(reader.pages, start=1):
        body = (page.extract_text() or "").strip()
        words += len(body.split())
        pages.append(f"=== page {number} ===\n{body}")

    stem = pathlib.Path(text_path).stem
    out_file = OUT_DIR / f"{item_id}-{stem}.txt"
    header = (
        f"{item_id} - {title}\n"
        f"Source: {text_path}\n"
        f"Pages: {len(reader.pages)}\n"
        f"\nThis file is a derived extraction of the item above; the "
        f"manifest record in corpus/manifest.md is the authority for\n"
        f"what the item is and what it is FOR. Regenerate with "
        f"tools/extract_corpus.py.\n\n"
    )
    out_file.write_text(header + "\n\n".join(pages) + "\n", encoding="utf-8")
    return out_file, len(reader.pages), words


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    items = read_manifest()
    if not items:
        raise SystemExit("FAULT: no manifest entries found")

    rows = []
    for item_id, title, text_path in items:
        out_file, pages, words = extract(item_id, title, text_path)
        rows.append((item_id, title, text_path, out_file.name, pages, words))
        print(f"extracted {item_id}: {pages} pages, {words} words -> {out_file.name}")

    index = [
        "# Corpus outputs",
        "",
        "Derived text, one file per curated item, regenerated by",
        "`tools/extract_corpus.py` from `corpus/manifest.md`. The",
        "manifest is the record; nothing here curates anything.",
        "",
        "| Item | Title | Text | Output | Pages | Words |",
        "|---|---|---|---|---|---|",
    ]
    for item_id, title, text_path, out_name, pages, words in rows:
        index.append(
            f"| {item_id} | {title} | `{text_path}` | "
            f"`out/{out_name}` | {pages} | {words} |"
        )
    (OUT_DIR / "INDEX.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    print(f"index: {len(rows)} items -> {OUT_DIR / 'INDEX.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())